// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8yzRm9qWF8Cm5Mz_Ik6wxaxv0p93rNpU',
    appId: '1:952708629960:web:dac835f32ad16286fd6cfd',
    messagingSenderId: '952708629960',
    projectId: 'the-wall-b1ee8',
    authDomain: 'the-wall-b1ee8.firebaseapp.com',
    storageBucket: 'the-wall-b1ee8.appspot.com',
    measurementId: 'G-EFKVSSDF0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgutfx3tLVXoDKskuVehnUV_LcQRVruWE',
    appId: '1:952708629960:android:416760fb9cc4b9dcfd6cfd',
    messagingSenderId: '952708629960',
    projectId: 'the-wall-b1ee8',
    storageBucket: 'the-wall-b1ee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8vdrOz23JKxf1EP1TBUHSZfpSeopg940',
    appId: '1:952708629960:ios:ee11951f6a05b75afd6cfd',
    messagingSenderId: '952708629960',
    projectId: 'the-wall-b1ee8',
    storageBucket: 'the-wall-b1ee8.appspot.com',
    iosBundleId: 'com.example.theWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8vdrOz23JKxf1EP1TBUHSZfpSeopg940',
    appId: '1:952708629960:ios:ee11951f6a05b75afd6cfd',
    messagingSenderId: '952708629960',
    projectId: 'the-wall-b1ee8',
    storageBucket: 'the-wall-b1ee8.appspot.com',
    iosBundleId: 'com.example.theWall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8yzRm9qWF8Cm5Mz_Ik6wxaxv0p93rNpU',
    appId: '1:952708629960:web:6c5391b55793ed55fd6cfd',
    messagingSenderId: '952708629960',
    projectId: 'the-wall-b1ee8',
    authDomain: 'the-wall-b1ee8.firebaseapp.com',
    storageBucket: 'the-wall-b1ee8.appspot.com',
    measurementId: 'G-CF3HKYPG7F',
  );
}
